{
  try {
    in.reset();
  }
 catch (  IOException e) {
  }
}
