{
  try {
    breakpoint.afterProcess(exchange,processor,definition,timeTaken);
  }
 catch (  Throwable e) {
    LOG.warn("Exception occurred in breakpoint: " + breakpoint + ". This exception will be ignored.",e);
  }
}
