{
  try {
    checkStatus(result);
    onCompleted(result);
  }
 catch (  Exception e) {
    failed(e);
  }
}
