{
  Exception exception=exchange.getException();
  if (exception == null) {
    return exchange;
  }
  try {
    if (fallback != null) {
      if (exchange.getProperty(Exchange.FAILURE_ENDPOINT) == null) {
        exchange.setProperty(Exchange.FAILURE_ENDPOINT,exchange.getProperty(Exchange.TO_ENDPOINT));
      }
      exchange.setProperty(Exchange.EXCEPTION_HANDLED,true);
      exchange.setProperty(Exchange.EXCEPTION_CAUGHT,exception);
      exchange.setException(null);
      exchange.removeProperty(Exchange.REDELIVERY_EXHAUSTED);
      try {
        LOG.debug("Running fallback: {}",exchange);
        fallback.process(exchange,callback);
      }
 catch (      Exception e) {
        exchange.setException(e);
      }
    }
  }
  finally {
    LOG.debug("Running fallback: {} success",exchange);
    callback.done(false);
  }
  return exchange;
}
