{
  Exception e=(Exception)mock.getExchanges().get(0).getProperty(Exchange.EXCEPTION_CAUGHT);
  assertNotNull("Expected excpetion " + cl.getName() + " missing",e);
  if (e.getClass() != cl) {
    String stackTrace=getStrackTrace(e);
    fail("Exception  " + cl.getName() + " excpected, but was "+ e.getClass().getName()+ ": "+ stackTrace);
  }
  if (expectedCauseClass != null) {
    Throwable cause=e.getCause();
    assertNotNull("Expected cause exception" + expectedCauseClass.getName() + " missing",cause);
    if (expectedCauseClass != cause.getClass()) {
      fail("Cause exception " + expectedCauseClass.getName() + " expected, but was "+ cause.getClass().getName()+ ": "+ getStrackTrace(e));
    }
  }
}
