{
  resultEndpoint1.expectedMessageCount(0);
  try {
    template1.sendBody(record1);
    fail("Should have thrown an exception");
  }
 catch (  CamelExecutionException e) {
    Assert.isInstanceOf(Exception.class,e.getCause());
  }
  resultEndpoint1.assertIsSatisfied();
}
