{
  log.info("Recieved hang up - stopping the main instance.");
  try {
    mainInstance.stop();
  }
 catch (  Exception ex) {
    log.warn(ex);
  }
}
