{
  for (  CatchProcessor catchClause : catchClauses) {
    if (catchClause.catches(e)) {
      Exchange localExchange=exchange.copy();
      localExchange.getIn().setHeader("caught.exception",e);
      localExchange.setException(null);
      try {
        catchClause.process(localExchange);
        ExchangeHelper.copyResults(exchange,localExchange);
      }
 catch (      Exception e1) {
        LOG.warn("Caught exception inside catch clause: " + e1,e1);
        throw e1;
      }
      return;
    }
  }
  if (finallyProcessor == null) {
    throw e;
  }
}
