{
  try {
    template.sendBody("direct:fail","Hello World");
    fail("Should have thrown an exception");
  }
 catch (  Exception e) {
    assertIsInstanceOf(IllegalArgumentException.class,e.getCause());
  }
  assertEquals(7,events.size());
  assertIsInstanceOf(CamelContextStartingEvent.class,events.get(0));
  assertIsInstanceOf(RouteStartedEvent.class,events.get(1));
  assertIsInstanceOf(RouteStartedEvent.class,events.get(2));
  assertIsInstanceOf(CamelContextStartedEvent.class,events.get(3));
  assertIsInstanceOf(ExchangeCreatedEvent.class,events.get(4));
  assertIsInstanceOf(ExchangeFailureEvent.class,events.get(5));
  assertIsInstanceOf(ExchangeSentEvent.class,events.get(6));
  assertEquals(3,events2.size());
  context.stop();
  assertIsInstanceOf(ExchangeCreatedEvent.class,events2.get(0));
  assertIsInstanceOf(ExchangeFailureEvent.class,events2.get(1));
  assertIsInstanceOf(ExchangeSentEvent.class,events2.get(2));
  assertEquals(11,events.size());
  assertIsInstanceOf(CamelContextStoppingEvent.class,events.get(7));
  assertIsInstanceOf(RouteStoppedEvent.class,events.get(8));
  assertIsInstanceOf(RouteStoppedEvent.class,events.get(9));
  assertIsInstanceOf(CamelContextStoppedEvent.class,events.get(10));
  assertEquals(3,events2.size());
}
