{
  try {
    super.setUp();
    fail("Should have thrown an exception");
  }
 catch (  ResolveEndpointFailedException e) {
    assertTrue(e.getMessage().endsWith("Unknown parameters=[{foo=bar}]"));
  }
}
