{
  throwFaultTest("direct:error",1);
}
